### ISSUE TITLE
boot nodes seems invalid now

### ISSUE THREAD

**Issue by CSeanXu** [hoosmartchain/hoo-smartchain#2]
Recentely, my hsc node fails connecting to P2P peers.

My guess is that the 3 boot nodes defined in the code are all dead.

Could the team kindly check it?

**Comment by vvvictorlee** [comment]
> Recentely, my hsc node fails connecting to P2P peers.
> 
> My guess is that the 3 boot nodes defined in the code are all dead.
> 
> Could the team kindly check it?

https://github.com/hoosmartchain/hsc-enode-list
